version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: .deploy/Dockerfile
    image: web-laundry
    container_name: web-laundry-app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
        - "80:80"
